[General]
TcpServerPort=5760
ReportStats=false

[UartEndpoint flight_controller]
Device=/dev/ttyACM0
Baud=115200

[UdpEndpoint ros2_node]
Address=127.0.0.1
Port=14550
Mode=Normal

[UdpEndpoint mission_planner]
Address=192.168.1.10
Port=14550
Mode=Normal
